version: '3'
services:
  database:
    image: "postgres:13.4" # same as what is running on AWS
    restart: always
    env_file:
      - database.env # configure postgres
    ports:
      - "5432:5432"
    volumes:
      # copy the sql script to create tables
      - ../.devops/postgres/pre-liquibase-init.sql:/docker-entrypoint-initdb.d/pre-liquibase-init.sql
  redis:
    image: "redis:6.2.6"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
